version: 2.1
workflows:
  main:
    jobs:
      - build
      - unit-php56:
          requires:
            - build
      - unit-php70:
          requires:
            - build
      - unit-php71:
          requires:
            - build
      - unit-php72:
          requires:
            - build
      - unit-php73:
          requires:
            - build
          coverage: true
      - lint:
          requires:
            - build

job-references:
  mysql_image: &mysql_image
    circleci/mysql:5

  restore_composer: &restore_composer
    keys:
      - v1-dependencies-{{ checksum "composer.json" }}
      - v1-dependencies-

  install_composer: &install_composer
    name: "Install Composer dependencies"
    command: composer install -n --prefer-dist

  save_composer: &save_composer
    key: v1-dependencies-{{ checksum "composer.json" }}
    paths:
      - vendor

  restore_composer_no_dev: &restore_composer_no_dev
    keys:
      - v1-dependencies-no-dev-{{ checksum "composer.json" }}
      - v1-dependencies-no-dev-
      - v1-dependencies-

  install_composer_no_dev: &install_composer_no_dev
    name: "Install Composer dependencies"
    command: composer install -n --prefer-dist --no-dev

  save_composer_no_dev: &save_composer_no_dev
    key: v1-dependencies-no-dev-{{ checksum "composer.json" }}
    paths:
      - vendor

  restore_npm: &restore_npm
    keys:
      - node-v1-{{ checksum "package.json" }}
      - node-v1-

  install_npm: &install_npm
    name: "Install NPM dependencies"
    command: |
      sudo npm install --global gulp-cli
      npm ci

  save_npm: &save_npm
    key: node-v1-{{ checksum "package.json" }}
    paths:
      - node_modules

  unit_test: &unit_test
    parameters:
      coverage:
        type: boolean
        default: false
    steps:
      - checkout

      - restore_cache: *restore_composer_no_dev
      - run: *install_composer_no_dev
      - save_cache: *save_composer_no_dev

      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm

      - attach_workspace:
          at: dist

      - run:
          name: "Prepare WordPress"
          command: |
            rm -rf /tmp/wordpress-tests-lib /tmp/wordpress
            sudo apt-get update && sudo apt-get install subversion default-mysql-client
            sudo -E docker-php-ext-install mysqli
            ./bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      - run:
          name: "Run Tests"
          command: gulp unit
      - when:
          condition: <<parameters.coverage>>
          steps:
            - run:
                name: Upload Coverage Results
                command: bash <(curl -s https://codecov.io/bash) -f clover.xml -t ${CODECOV_TOKEN}
            - run:
                name: Collect test metadata
                command: |
                  mkdir -p ~/phpunit
                  mv junit.xml ~/phpunit/
                when: always
            - store_test_results:
                path: ~/phpunit
            - store_artifacts:
                path: ~/phpunit

jobs:
  build:
    docker:
      - image: circleci/php:7.3-node
    steps:
      - checkout

      - restore_cache: *restore_composer
      - run: *install_composer
      - save_cache: *save_composer

      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm
      - run:
          name: "Build"
          command: gulp build
      - persist_to_workspace:
          root: dist
          paths:
            - "*"

  unit-php56:
    <<: *unit_test
    docker:
      - image: circleci/php:5.6-node
      - image: *mysql_image

  unit-php70:
    <<: *unit_test
    docker:
      - image: circleci/php:7.0-node
      - image: *mysql_image

  unit-php71:
    <<: *unit_test
    docker:
      - image: circleci/php:7.1-node
      - image: *mysql_image

  unit-php72:
    <<: *unit_test
    docker:
      - image: circleci/php:7.2-node
      - image: *mysql_image

  unit-php73:
    <<: *unit_test
    docker:
      - image: circleci/php:7.3-node
      - image: *mysql_image

  lint:
    docker:
      - image: circleci/php:7.3-node
    steps:
      - checkout

      - restore_cache: *restore_composer
      - run: *install_composer
      - save_cache: *save_composer

      - restore_cache: *restore_npm
      - run: *install_npm
      - save_cache: *save_npm

      - attach_workspace:
          at: dist

      - run:
          name: "Install php-ast"
          command: |
            sudo pecl install ast
            echo 'extension=ast.so' | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run:
          name: "Lint"
          command: gulp lint
